spring:
  application:
    name: ecommerce-api
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?profileSQL=true
    username: ${db.username}
    password: ${db.password}
    hikari:
      maximum-pool-size: 100

  jpa:
    hibernate:
      ddl-auto: none
logging:
  level:
    root: INFO
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
#    org.springframework.jdbc.core.StatementCreatorUtils: DEBUG